import {StudentRegistrationPage} from '../page-objects/studentRegistrationPage'

// Untuk memanggil class yang ada di student page agar dapat digunakan pada test case
const studentRegistrationPage = new StudentRegistrationPage()

// Aksi yang akan dilakukan sebelum setiap test case dijalankan
beforeEach(() => {
    studentRegistrationPage.navigate()
})

describe('Register Test', () => {
    // Data untuk menjankan testcase
    const dataFirstName = 'First Name'
    const dataLastName = 'Last Name'
    const dataGender = 'Male'
    const dataPhoneNumber = '08123456789'
    const dataEmail = 'tes@tes.com'
    const dataDate = 25
    const dataSubjects = 'E'
    const dataHobbies = 'Sports'
    const dataUploadFile = 'images.png'
    const dataAddress = 'Kota Tangerang, Banten, Indonesia'
    const dataState = 'NCR'
    const dataCity = 'Delhi'

    it('1. Valid register', () => {
        studentRegistrationPage.inputFirstName(dataFirstName)
        studentRegistrationPage.inputLastName(dataLastName)
        studentRegistrationPage.chooseGender(dataGender)
        studentRegistrationPage.inputPhoneNumber(dataPhoneNumber)
        studentRegistrationPage.inputEmail(dataEmail)
        studentRegistrationPage.chooseDate(dataDate)
        studentRegistrationPage.chooseSubjects(dataSubjects)
        studentRegistrationPage.chooseHobbies(dataHobbies)
        studentRegistrationPage.uploadFile(dataUploadFile)
        studentRegistrationPage.inputAddress(dataAddress)
        studentRegistrationPage.chooseStateCity(dataState, dataCity)
        studentRegistrationPage.clickSubmit()
    })
    it('2. Empty First Name register', () => {
        // studentRegistrationPage.inputFirstName(dataFirstName)
        studentRegistrationPage.inputLastName(dataLastName)
        studentRegistrationPage.chooseGender(dataGender)
        studentRegistrationPage.inputPhoneNumber(dataPhoneNumber)
        studentRegistrationPage.inputEmail(dataEmail)
        studentRegistrationPage.chooseDate(dataDate)
        studentRegistrationPage.chooseSubjects(dataSubjects)
        studentRegistrationPage.chooseHobbies(dataHobbies)
        studentRegistrationPage.uploadFile(dataUploadFile)
        studentRegistrationPage.inputAddress(dataAddress)
        studentRegistrationPage.chooseStateCity(dataState, dataCity)
        studentRegistrationPage.clickSubmit()
    })
    it('3. Empty Last Name register', () => {
        studentRegistrationPage.inputFirstName(dataFirstName)
        // studentRegistrationPage.inputLastName(dataLastName)
        studentRegistrationPage.chooseGender(dataGender)
        studentRegistrationPage.inputPhoneNumber(dataPhoneNumber)
        studentRegistrationPage.inputEmail(dataEmail)
        studentRegistrationPage.chooseDate(dataDate)
        studentRegistrationPage.chooseSubjects(dataSubjects)
        studentRegistrationPage.chooseHobbies(dataHobbies)
        studentRegistrationPage.uploadFile(dataUploadFile)
        studentRegistrationPage.inputAddress(dataAddress)
        studentRegistrationPage.chooseStateCity(dataState, dataCity)
        studentRegistrationPage.clickSubmit()
    })
    it('4. Empty gender register', () => {
        studentRegistrationPage.inputFirstName(dataFirstName)
        studentRegistrationPage.inputLastName(dataLastName)
        // studentRegistrationPage.chooseGender(dataGender)
        studentRegistrationPage.inputPhoneNumber(dataPhoneNumber)
        studentRegistrationPage.inputEmail(dataEmail)
        studentRegistrationPage.chooseDate(dataDate)
        studentRegistrationPage.chooseSubjects(dataSubjects)
        studentRegistrationPage.chooseHobbies(dataHobbies)
        studentRegistrationPage.uploadFile(dataUploadFile)
        studentRegistrationPage.inputAddress(dataAddress)
        studentRegistrationPage.chooseStateCity(dataState, dataCity)
        studentRegistrationPage.clickSubmit()
    })
    it('5. Empty Phone Number register', () => {
        studentRegistrationPage.inputFirstName(dataFirstName)
        studentRegistrationPage.inputLastName(dataLastName)
        studentRegistrationPage.chooseGender(dataGender)
        // studentRegistrationPage.inputPhoneNumber(dataPhoneNumber)
        studentRegistrationPage.inputEmail(dataEmail)
        studentRegistrationPage.chooseDate(dataDate)
        studentRegistrationPage.chooseSubjects(dataSubjects)
        studentRegistrationPage.chooseHobbies(dataHobbies)
        studentRegistrationPage.uploadFile(dataUploadFile)
        studentRegistrationPage.inputAddress(dataAddress)
        studentRegistrationPage.chooseStateCity(dataState, dataCity)
        studentRegistrationPage.clickSubmit()
    })
    it('6. Empty Email register', () => {
        studentRegistrationPage.inputFirstName(dataFirstName)
        studentRegistrationPage.inputLastName(dataLastName)
        studentRegistrationPage.chooseGender(dataGender)
        studentRegistrationPage.inputPhoneNumber(dataPhoneNumber)
        // studentRegistrationPage.inputEmail(dataEmail)
        studentRegistrationPage.chooseDate(dataDate)
        studentRegistrationPage.chooseSubjects(dataSubjects)
        studentRegistrationPage.chooseHobbies(dataHobbies)
        studentRegistrationPage.uploadFile(dataUploadFile)
        studentRegistrationPage.inputAddress(dataAddress)
        studentRegistrationPage.chooseStateCity(dataState, dataCity)
        studentRegistrationPage.clickSubmit()
    })
    it('7. Empty Date register', () => {
        studentRegistrationPage.inputFirstName(dataFirstName)
        studentRegistrationPage.inputLastName(dataLastName)
        studentRegistrationPage.chooseGender(dataGender)
        studentRegistrationPage.inputPhoneNumber(dataPhoneNumber)
        studentRegistrationPage.inputEmail(dataEmail)
        // studentRegistrationPage.chooseDate(dataDate)
        studentRegistrationPage.chooseSubjects(dataSubjects)
        studentRegistrationPage.chooseHobbies(dataHobbies)
        studentRegistrationPage.uploadFile(dataUploadFile)
        studentRegistrationPage.inputAddress(dataAddress)
        studentRegistrationPage.chooseStateCity(dataState, dataCity)
        studentRegistrationPage.clickSubmit()
    })
    it('8. Empty Subjects register', () => {
        studentRegistrationPage.inputFirstName(dataFirstName)
        studentRegistrationPage.inputLastName(dataLastName)
        studentRegistrationPage.chooseGender(dataGender)
        studentRegistrationPage.inputPhoneNumber(dataPhoneNumber)
        studentRegistrationPage.inputEmail(dataEmail)
        studentRegistrationPage.chooseDate(dataDate)
        // studentRegistrationPage.chooseSubjects(dataSubjects)
        studentRegistrationPage.chooseHobbies(dataHobbies)
        studentRegistrationPage.uploadFile(dataUploadFile)
        studentRegistrationPage.inputAddress(dataAddress)
        studentRegistrationPage.chooseStateCity(dataState, dataCity)
        studentRegistrationPage.clickSubmit()
    })
    it('9. Empty choose hobbies register', () => {
        studentRegistrationPage.inputFirstName(dataFirstName)
        studentRegistrationPage.inputLastName(dataLastName)
        studentRegistrationPage.chooseGender(dataGender)
        studentRegistrationPage.inputPhoneNumber(dataPhoneNumber)
        studentRegistrationPage.inputEmail(dataEmail)
        studentRegistrationPage.chooseDate(dataDate)
        studentRegistrationPage.chooseSubjects(dataSubjects)
        // studentRegistrationPage.chooseHobbies(dataHobbies)
        studentRegistrationPage.uploadFile(dataUploadFile)
        studentRegistrationPage.inputAddress(dataAddress)
        studentRegistrationPage.chooseStateCity(dataState, dataCity)
        studentRegistrationPage.clickSubmit()
    })
    it('10. Not upload file in register', () => {
        studentRegistrationPage.inputFirstName(dataFirstName)
        studentRegistrationPage.inputLastName(dataLastName)
        studentRegistrationPage.chooseGender(dataGender)
        studentRegistrationPage.inputPhoneNumber(dataPhoneNumber)
        studentRegistrationPage.inputEmail(dataEmail)
        studentRegistrationPage.chooseDate(dataDate)
        studentRegistrationPage.chooseSubjects(dataSubjects)
        studentRegistrationPage.chooseHobbies(dataHobbies)
        // studentRegistrationPage.uploadFile(dataUploadFile)
        studentRegistrationPage.inputAddress(dataAddress)
        studentRegistrationPage.chooseStateCity(dataState, dataCity)
        studentRegistrationPage.clickSubmit()
    })
    it('11. Empty address register', () => {
        studentRegistrationPage.inputFirstName(dataFirstName)
        studentRegistrationPage.inputLastName(dataLastName)
        studentRegistrationPage.chooseGender(dataGender)
        studentRegistrationPage.inputPhoneNumber(dataPhoneNumber)
        studentRegistrationPage.inputEmail(dataEmail)
        studentRegistrationPage.chooseDate(dataDate)
        studentRegistrationPage.chooseSubjects(dataSubjects)
        studentRegistrationPage.chooseHobbies(dataHobbies)
        studentRegistrationPage.uploadFile(dataUploadFile)
        // studentRegistrationPage.inputAddress(dataAddress)
        studentRegistrationPage.chooseStateCity(dataState, dataCity)
        studentRegistrationPage.clickSubmit()
    })
    it('12. Empty state and city register', () => {
        studentRegistrationPage.inputFirstName(dataFirstName)
        studentRegistrationPage.inputLastName(dataLastName)
        studentRegistrationPage.chooseGender(dataGender)
        studentRegistrationPage.inputPhoneNumber(dataPhoneNumber)
        studentRegistrationPage.inputEmail(dataEmail)
        studentRegistrationPage.chooseDate(dataDate)
        studentRegistrationPage.chooseSubjects(dataSubjects)
        studentRegistrationPage.chooseHobbies(dataHobbies)
        studentRegistrationPage.uploadFile(dataUploadFile)
        studentRegistrationPage.inputAddress(dataAddress)
        // studentRegistrationPage.chooseStateCity(dataState, dataCity)
        studentRegistrationPage.clickSubmit()
    })
    it('13. Input hobbies more than 1', () => {
        studentRegistrationPage.inputFirstName(dataFirstName)
        studentRegistrationPage.inputLastName(dataLastName)
        studentRegistrationPage.chooseGender(dataGender)
        studentRegistrationPage.inputPhoneNumber(dataPhoneNumber)
        studentRegistrationPage.inputEmail(dataEmail)
        studentRegistrationPage.chooseDate(dataDate)
        studentRegistrationPage.chooseSubjects(dataSubjects)
        studentRegistrationPage.chooseHobbies(dataHobbies)
        studentRegistrationPage.chooseHobbies('Reading')
        studentRegistrationPage.chooseHobbies('Music')
        studentRegistrationPage.uploadFile(dataUploadFile)
        studentRegistrationPage.inputAddress(dataAddress)
        studentRegistrationPage.chooseStateCity(dataState, dataCity)
        studentRegistrationPage.clickSubmit()
    })
})